language: python
python: "3.5"

env:
  matrix:
    - TOXENV=flake8
    - TOXENV=checkdocs
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=behave

install:
  - pip install tox coveralls
before_script:
  - mkdir -p shippable/{codecoverage,testresults}
script:
  - tox -e $TOXENV
after_success:
  - coveralls || true
  - mv -v coverage.xml shippable/codecoverage/
  - mv -v tests/reports/* shippable/testresults/
notifications:
  slack: organice:2v4ZfYaW6KonOr5RyJqjyU92
  webhooks:
    urls:
      - https://readthedocs.org/build/django-organice
    on_start: never
    on_failure: never
    on_success: always
