# https://app.shippable.com/projects/544620bbb904a4b21567c427
language: python
python:
  - 2.7
  - 3.3
  - 3.4
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - python setup.py install
  - pip install flake8
  - pip install coveralls
before_script:
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults
  - flake8
script:
  - coverage run setup.py test
after_success:
  - coverage report
  - coverage xml
  - coveralls
  - mv -v coverage.xml shippable/codecoverage/
  - mv -v unittests.xml shippable/testresults/
notifications:
  slack:
    rooms:
      - organice:uPGToVwXE2IYAwn4hFFudPJ5#notifications
