language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install flake8 tox coverage==3.7.1 coveralls
before_script:
  - flake8
  - mkdir -p shippable/{codecoverage,testresults}
script:
  - tox -e py${TRAVIS_PYTHON_VERSION/\./}
after_success:
  - coverage report
  - coverage xml
  - mv -v coverage.xml shippable/codecoverage/
  - mv -v unittests.xml shippable/testresults/
  - coveralls || true
notifications:
  slack: organice:2v4ZfYaW6KonOr5RyJqjyU92
