language: python
python: 3.4
env:  # generate list with: $ tox -l | xargs -I ITEM echo "  - TOXENV="ITEM
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - pip install flake8 tox coverage==3.7.1 coveralls
before_script:
  - flake8
  - mkdir -p shippable/{codecoverage,testresults}
script:
  - tox
after_success:
  - coverage report
  - coverage xml
  - mv -v coverage.xml shippable/codecoverage/
  - mv -v unittests.xml shippable/testresults/
  - coveralls || true
notifications:
  slack:
    rooms:
      - organice:uPGToVwXE2IYAwn4hFFudPJ5#notifications
